# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

permalink: /:categories/:year-:month-:day/:title
# permalink: /:categories/:title
timezone: Asia/Tokyo
name: おせち 通販 | 2015
description: 2015年のおせちに関する情報を発信します
url: http://おせち.co
author:
  name: c.h
  email: chr@chrhsmt.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']
excerpt_separator: "<!-- more -->"

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

paginate: 5
paginate_path: "/page:num"

HEADER_IMAGE_WIDTH: 980
HEADER_IMAGE_HEIGHT: 250
